# Generated by Django 5.2.8 on 2025-11-24 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('real_estate', 'Real Estate'), ('retirals', 'Retirals'), ('others', 'Others')], max_length=50)),
                ('number_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('typical_initial_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('appreciation_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('typical_return_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('uncertainty_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('volatile', 'Volatile')], default='none', max_length=20)),
                ('basis', models.CharField(default='single', max_length=20)),
                ('liquid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('number_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('pertains_to', models.CharField(choices=[('household', 'Household'), ('adult', 'Adult'), ('child', 'Child'), ('house', 'House'), ('vehicle', 'Vehicle'), ('others', 'Others')], default='household', max_length=50)),
                ('typical_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frequency', models.CharField(default='annual', max_length=20)),
                ('inflation_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('insurance_indicator', models.BooleanField(default=False)),
                ('copay_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('uncertainty_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('volatile', 'Volatile')], default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('asset_return', 'Asset Return'), ('others', 'Others')], max_length=50)),
                ('number_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('typical_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frequency', models.CharField(default='annual', max_length=20)),
                ('growth_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('efficiency_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('uncertainty_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('volatile', 'Volatile')], default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('initial_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('appreciation_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('return_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('swp_possible', models.BooleanField(default=False)),
                ('uncertainty_level', models.CharField(default='none', max_length=20)),
                ('liquid', models.BooleanField(default=False)),
                ('is_business_pledged', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('pertains_to', models.CharField(default='household', max_length=50)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('typical_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frequency', models.CharField(default='annual', max_length=20)),
                ('inflation_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('insurance_indicator', models.BooleanField(default=False)),
                ('copay_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('uncertainty_level', models.CharField(default='none', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('earning_adult', 'Earning Adult'), ('dependent_adult', 'Dependent Adult'), ('child', 'Child'), ('pet', 'Pet')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('retirement_age', models.IntegerField(blank=True, default=60, null=True)),
                ('has_pf', models.BooleanField(default=False)),
                ('health_insurance', models.BooleanField(default=False)),
                ('allowance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('age_of_graduation_start', models.IntegerField(blank=True, default=18, null=True)),
                ('age_of_expenses_end', models.IntegerField(blank=True, default=24, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelling_start_year', models.IntegerField(default=2024)),
                ('modelling_end_year', models.IntegerField(default=2044)),
                ('bank_rate', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('wealth_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('income_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('expense_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('rented_house', models.BooleanField(default=False)),
                ('financial_investment_areas', models.JSONField(blank=True, default=list)),
                ('physical_investment_areas', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('typical_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frequency', models.CharField(default='annual', max_length=20)),
                ('growth_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('efficiency_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('uncertainty_level', models.CharField(default='none', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
