# Generated by Django 5.2.3 on 2025-11-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget_type',
            field=models.CharField(choices=[('needs', 'Needs (Survival)'), ('wants', 'Wants (Lifestyle)'), ('savings', 'Savings/Investments')], default='needs', max_length=20),
        ),
        migrations.AddField(
            model_name='expensemaster',
            name='budget_type',
            field=models.CharField(choices=[('needs', 'Needs (Survival)'), ('wants', 'Wants (Lifestyle)'), ('savings', 'Savings/Investments')], default='needs', max_length=20),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='emergency_fund_months',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='has_private_health_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='needs_percent',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='pause_retirals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='savings_percent',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='wants_percent',
            field=models.IntegerField(default=30),
        ),
    ]
