# Generated by Django 5.2.3 on 2026-02-13 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_budget_type_expensemaster_budget_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='current_tier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='num_houses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='num_vehicles',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='income',
            name='linked_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.asset'),
        ),
        migrations.AddField(
            model_name='income',
            name='withdrawal_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='CashflowProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('income_splits', models.JSONField(blank=True, default=dict)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expense_needs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expense_wants', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_cashflow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('excess_cashflow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('shortfall', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observations', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('user', 'year')},
            },
        ),
    ]
