# Generated by Django 5.2.3 on 2026-02-13 01:28

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_familyprofile_current_tier_familyprofile_num_houses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyprofile',
            name='modelling_end_year',
            field=models.IntegerField(default=finance.models._current_year_plus_20),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='modelling_start_year',
            field=models.IntegerField(default=finance.models._current_year),
        ),
    ]
