# Generated by Django 5.2.3 on 2026-02-14 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0004_alter_familyprofile_modelling_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_profile', to='core.scenarioprofile'),
        ),
    ]
