# Generated by Django 5.2.3 on 2026-02-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_familyprofile_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='has_pet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expensemaster',
            name='pertains_to',
            field=models.CharField(choices=[('household', 'Household'), ('adult', 'Adult'), ('child', 'Child'), ('house', 'House'), ('vehicle', 'Vehicle'), ('pet', 'Pet'), ('dependent_adult', 'Dependent Adult'), ('others', 'Others')], default='household', max_length=50),
        ),
    ]
