# Generated by Django 5.2.3 on 2026-02-14 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_type', models.CharField(choices=[('FOUNDER', 'Startup Founder'), ('RETIREMENT', 'Retirement Planning'), ('R2I', 'Returning to India'), ('HALF_FIRE', 'Half FIRE / Part-time'), ('TERMINATION', 'Job Loss / Severance')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_age', models.IntegerField(blank=True, null=True)),
                ('retirement_age', models.IntegerField(blank=True, null=True)),
                ('life_expectancy', models.IntegerField(blank=True, null=True)),
                ('pension_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pension_start_age', models.IntegerField(blank=True, null=True)),
                ('gratuity_lumpsum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parttime_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parttime_start_month', models.IntegerField(blank=True, help_text='Months from now', null=True)),
                ('full_fire_target_month', models.IntegerField(blank=True, help_text='Months from now', null=True)),
                ('severance_lumpsum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('severance_month_count', models.IntegerField(blank=True, help_text='Months of salary', null=True)),
                ('income_restart_month', models.IntegerField(blank=True, help_text='Months from now when income restarts', null=True)),
                ('restart_monthly_income', models.DecimalField(blank=True, decimal_places=2, help_text='Salary after restart', max_digits=12, null=True)),
                ('venture_bootstrapped', models.BooleanField(blank=True, default=False, null=True)),
                ('bootstrap_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scenario Profile',
                'verbose_name_plural': 'Scenario Profiles',
            },
        ),
    ]
