# Generated by Django 5.2.3 on 2026-02-14 12:17

from django.db import migrations


def create_founder_scenarios_for_existing_users(apps, schema_editor):
    """
    Create ScenarioProfile with scenario_type='FOUNDER' for all existing users.
    This ensures backward compatibility with the old Founder FIRE flow.
    """
    User = apps.get_model('auth', 'User')
    ScenarioProfile = apps.get_model('core', 'ScenarioProfile')
    FamilyProfile = apps.get_model('finance', 'FamilyProfile')

    for user in User.objects.all():
        # Create FOUNDER scenario for existing users
        scenario, created = ScenarioProfile.objects.get_or_create(
            user=user,
            defaults={'scenario_type': 'FOUNDER'}
        )

        # Link family profile to scenario
        try:
            profile = FamilyProfile.objects.get(user=user)
            profile.scenario = scenario
            profile.save()
        except FamilyProfile.DoesNotExist:
            # User doesn't have a profile yet, skip
            pass


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: delete all FOUNDER scenarios.
    """
    ScenarioProfile = apps.get_model('core', 'ScenarioProfile')
    ScenarioProfile.objects.filter(scenario_type='FOUNDER').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0005_familyprofile_scenario'),  # Ensure scenario field exists
    ]

    operations = [
        migrations.RunPython(
            create_founder_scenarios_for_existing_users,
            reverse_migration
        ),
    ]
