# Generated by Django 5.2.3 on 2026-03-28 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_founder_scenarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRatePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquid_return_pct', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('semi_liquid_return_pct', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('growth_return_pct', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('property_appreciation_pct', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('property_rental_yield_pct', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('needs_inflation_pct', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('wants_inflation_pct', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
                ('passive_growth_pct', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('swr_rate_pct', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Rate Preferences',
            },
        ),
    ]
