# Generated by Django 5.2.3 on 2026-03-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_user_rate_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioprofile',
            name='founder_salary_start_month',
            field=models.IntegerField(blank=True, help_text='Months from now when founder starts drawing salary from the venture', null=True),
        ),
    ]
