# Generated by Django 6.0.4 on 2026-04-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_founder_salary_start_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviourEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('event', models.CharField(db_index=True, max_length=64)),
                ('properties', models.JSONField(default=dict)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['session_key', 'ts'], name='core_behavi_session_f0e370_idx'), models.Index(fields=['event', 'ts'], name='core_behavi_event_ddaa4d_idx')],
            },
        ),
    ]
