# Generated by Django 5.2.3 on 2026-04-10 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_behaviour_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEncryption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdf_salt', models.CharField(max_length=64)),
                ('passphrase_hint', models.CharField(blank=True, default='', max_length=200)),
                ('verification_token', models.TextField()),
                ('encrypted_payload', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encryption', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Encryption',
            },
        ),
    ]
