# Generated by Django 6.0.4 on 2026-04-25 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_user_encryption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_type', models.CharField(blank=True, default='', max_length=20)),
                ('answers_flat', models.JSONField(default=dict)),
                ('answers_nested', models.JSONField(default=dict)),
                ('answers_hash', models.CharField(blank=True, default='', max_length=64)),
                ('tier1_results', models.JSONField(blank=True, null=True)),
                ('tier2_results', models.JSONField(blank=True, null=True)),
                ('mc_results', models.JSONField(blank=True, null=True)),
                ('asha_advice', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Flow State',
            },
        ),
    ]
