# Generated by Django 5.2.8 on 2025-11-24 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('growth', 'Growth'), ('scaling', 'Scaling')], default='idea', max_length=20)),
                ('target_runway_months', models.IntegerField(default=12)),
                ('business_failure_probability', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartupCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_recurring', models.BooleanField(default=False)),
                ('frequency', models.CharField(default='one_time', max_length=20)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='ventures.venture')),
            ],
        ),
        migrations.CreateModel(
            name='FounderSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_month_offset', models.IntegerField(default=0)),
                ('end_month_offset', models.IntegerField(default=12)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='ventures.venture')),
            ],
        ),
    ]
